# modules/organization/organization_schemas.py
from pydantic import BaseModel, EmailStr
from uuid import UUID
from typing import Optional
from datetime import datetime

class OrganizationBaseSchema(BaseModel):
    name: str
    email: Optional[EmailStr] = None

class OrganizationCreateSchema(OrganizationBaseSchema):
    id: Optional[UUID] = None  # Can be provided by frontend or auto-generated by backend

class OrganizationResponseSchema(OrganizationBaseSchema):
    id: UUID
    created_at: datetime

    class Config:
        from_attributes = True  # Allows Pydantic to read SQLAlchemy models directly