version: '3.8'

services:
  backend:
    build: 
      context: ../..
      dockerfile: infra/docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../../engine/.env
    depends_on:
      - db
  
  frontend:
    build:
      context: ../../cpanel
    ports:
      - "3000:3000"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
