[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0

[program:postgresql]
command=/usr/lib/postgresql/<PG_VERSION>/bin/postgres -D /var/lib/postgresql/<PG_VERSION>/main -c config_file=/etc/postgresql/<PG_VERSION>/main/postgresql.conf
user=postgres
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:redis]
command=redis-server --protected-mode no
user=redis
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery]
command=poetry run celery -A engine.pipelines.tasks.celery_app worker --loglevel=info
directory=/app
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:web]
command=poetry run uvicorn main:app --host 0.0.0.0 --port 8000
directory=/app
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
