"""Add drive document models

Revision ID: 77694edb12d6
Revises: knowledge_rev
Create Date: 2026-06-17 15:13:44.168322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77694edb12d6'
down_revision: Union[str, Sequence[str], None] = 'knowledge_rev'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_documents',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('drive_file_id', sa.String(length=255), nullable=False),
    sa.Column('drive_folder_id', sa.String(length=255), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('web_view_link', sa.String(length=2048), nullable=True),
    sa.Column('web_content_link', sa.String(length=2048), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('last_modified_in_drive', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'processing', 'indexed', 'failed')", name='drive_documents_status_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'drive_file_id', name='uq_drive_documents_workspace_file_id'),
    schema='knowledge'
    )
    op.create_index(op.f('ix_knowledge_drive_documents_drive_file_id'), 'drive_documents', ['drive_file_id'], unique=False, schema='knowledge')
    op.create_index(op.f('ix_knowledge_drive_documents_drive_folder_id'), 'drive_documents', ['drive_folder_id'], unique=False, schema='knowledge')
    
    op.create_table('drive_document_chunks',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('drive_document_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('workspace_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('embedding_model', sa.String(length=255), nullable=True),
    sa.Column('embedding_created_at', sa.DateTime(), nullable=True),
    sa.Column('embedding_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drive_document_id'], ['knowledge.drive_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_document_id', 'sequence_number', name='uq_drive_document_chunks_doc_seq'),
    schema='knowledge'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drive_document_chunks', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_drive_documents_drive_folder_id'), table_name='drive_documents', schema='knowledge')
    op.drop_index(op.f('ix_knowledge_drive_documents_drive_file_id'), table_name='drive_documents', schema='knowledge')
    op.drop_table('drive_documents', schema='knowledge')
    # ### end Alembic commands ###
